# Generated by Django 4.2.11 on 2024-04-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="  კატეგორია"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name=" წიგნის დასახელება"),
                ),
                (
                    "page_count",
                    models.IntegerField(verbose_name=" ფურცლების რაოდენობა"),
                ),
                (
                    "author_name",
                    models.CharField(max_length=255, verbose_name=" წიგნის დასახელება"),
                ),
                (
                    "price",
                    models.FloatField(blank=True, null=True, verbose_name=" ფასი"),
                ),
                (
                    "published",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name=" შექმნის თარიღი"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="market.category",
                        verbose_name="  კატეგორია",
                    ),
                ),
            ],
        ),
    ]
