# Generated by Django 3.2.10 on 2024-04-12 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='  ავტორი')),
            ],
            options={
                'verbose_name': ' ავტორი',
                'verbose_name_plural': ' ავტორები',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='  კატეგორია')),
            ],
            options={
                'verbose_name': ' კატეგორია',
                'verbose_name_plural': ' კატეგორიები',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=' წიგნის დასახელება')),
                ('page_count', models.IntegerField(verbose_name=' ფურცლების რაოდენობა')),
                ('price', models.FloatField(blank=True, null=True, verbose_name=' ფასი')),
                ('image', models.ImageField(null=True, upload_to='mediafiles/')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=' შექმნის თარიღი')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='market.author', verbose_name='  ავტორი')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FKcategpry', to='market.category', verbose_name='  კატეგორია')),
            ],
            options={
                'verbose_name': ' წიგნი',
                'verbose_name_plural': ' წიგნები',
            },
        ),
    ]
