# Generated by Django 4.2.11 on 2024-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='mediafiles/'),
        ),
    ]
