# Generated by Django 3.2.10 on 2024-04-15 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20240412_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='FKAuthor', to='market.Author', verbose_name=' კატეგორია'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FKcategpry', to='market.category', verbose_name='კატეგორია'),
        ),
    ]
