# Generated by Django 4.2.11 on 2024-04-08 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0004_book_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": " ავტორი", "verbose_name_plural": " ავტორები"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": " წიგნი", "verbose_name_plural": " წიგნები"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": " კატეგორია",
                "verbose_name_plural": " კატეგორიები",
            },
        ),
    ]
