# Generated by Django 3.2.10 on 2024-04-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20240415_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FKcategpry', to='market.category', verbose_name='category'),
        ),
    ]
