# Generated by Django 4.2.11 on 2024-05-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0009_auto_20240415_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="stock",
            field=models.IntegerField(blank=True, null=True, verbose_name="stock"),
        ),
    ]
